---
title: "Medicines in the kitchen: A gender perspective of the ethnobotanical knowledge in Marrakshi households"
description: |
  Irene Teixidor-Toneu, Sara Elgadi, Hamza Zine, Ugo D’Ambrosio
author:
  - name: Vincent Manzanilla
    url: https://github.com/vincentmanz
    affiliation: BaseClear B.V / Datalabs
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: 200
  chunk_output_type: console
---

```{r setup, include=TRUE}

library(dplyr)
library(tidyr)
library(hrbrthemes)
library(ggplot2)
library(viridis)
```


```{r import data}

file <- read.csv("i-Marrakech_dataset.csv", sep=";")
df0 <- file %>% select(Sex,N_Pl_total, Freq_cooking ) %>% 
  mutate(Sex, Gender = case_when(
    Sex == "F" ~ "Women",
    Sex == "M" ~ "Men"))

```


## Linear model 

```{r linear model}
model1 <-
  glm(df0$N_Pl_total ~ df0$Gender * df0$Freq_cooking,
      family = quasipoisson,
      data = df0)
summary(model1)
```


## General overview

```{r nb plants per sex, fig.align="center", fig.width=8, fig.height=6}
df0 %>%
  ggplot(aes(x = Gender, y = N_Pl_total, fill = Gender)) +
  geom_boxplot(fill=c( "#00798c",  "#d1495b")) +
  geom_jitter(color = "black",
              size = 0.9,
              alpha = 0.9) +
  theme_ipsum(axis_title_size = 11) +
  theme(legend.position = "none",
        plot.title = element_text(size = 11)) +
  ylab("Total Number of Plants") +
  xlab("Gender") +
  ggtitle("Number of plants according to the gender - box plot")
 
```


## GLM prediction of number of plants according to frequency of cooking per men and women

```{r create trend lines data}
x <- seq(0, 28, 1)
men_coeff <- 3.588038 - 0.0197708 * x
women_coeff <- 3.588038 + 0.022439 * x
Men <- exp(men_coeff)
Women <- exp(women_coeff)

plants <- data.frame(x, Men, Women)
plants_long <- plants %>% 
  pivot_longer(!x, names_to = "Gender", values_to = "coeff")

```


 
```{r scatter plot trend line, layout="l-body-outset", fig.align="center", fig.width=8, fig.height=6}

ggplot() + 
  geom_point(data = df0, aes(x = Freq_cooking, y = N_Pl_total, color = Gender)) +
  geom_line(data = plants_long, aes(x, coeff, color= Gender))  +
  xlab("Cooking frequency") + 
  ylab("Total Number of Plants") +
  theme_ipsum(axis_title_size = 13) +
  scale_color_manual(values = c( "#00798c",  "#d1495b", "#00798c","#d1495b")) 
  

```

<center>
*Figure 2. Prediction of number of plants according to frequency of cooking per men and women based on a GLM with interactions (full model and results in ESM4).*
</center><br>
